{% set name = "prophet" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cfb7665962e983b05367f65f37692d9c8569a86335f3f163925ec89a128bfab

build:
  skip: true  # [python_impl == 'pypy']
  number: 0
  script_env:
    - PROPHET_REPACKAGE_CMDSTAN=false
    - PRECOMPILED_HEADERS=false
  script: {{ PYTHON }} -m pip install . -vv
  binary_has_prefix_files:
    - {{ SP_DIR|replace("\\", "/") }}/stan_model/prophet_model.bin
  ignore_prefix_files:
    - bin/cmdstan/src/stan/model/model_header.hpp.gch
    - bin/cmdstan/src/stan/model/main.d
    - bin/cmdstan/src/cmdstan/main.d

requirements:
  build:
    - {{ compiler('cxx') }}  # [unix]
  host:
    - python
    - pip
    - cmdstanpy >=1.0.4
    - cmdstan ==2.29.2
    - setuptools >=42
    - wheel >=0.37.0
    - tbb-devel

  run:
    - python
    # Are these dependencies still necessary?
    - setuptools >=42
    - wheel >=0.37.0
    - setuptools-git >=1.2
    # Pin the cmdstan version
    - cmdstan ==2.29.2
    # List below comes from Grayskull:
    - cmdstanpy >=1.0.4
    - numpy >=1.15.4
    - matplotlib-base >=2.0.0
    - pandas >=1.0.4
    - lunarcalendar >=0.0.9
    - convertdate >=2.1.2
    - holidays >=0.14.2
    - python-dateutil >=2.8.0
    - tqdm >=4.36.1

test:
  imports:
    - prophet
    - prophet.tests
  commands:
    - pip check
    - py.test -v --pyargs prophet
  requires:
    - pip
    - pytest

about:
  home: https://facebook.github.io/prophet/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic Forecasting Procedure
  description: |
    Implements a procedure for forecasting time series data based on an
    additive model where non-linear trends are fit with yearly, weekly, and
    daily seasonality, plus holiday effects. It works best with time series
    that have strong seasonal effects and several seasons of historical data.
    Prophet is robust to missing data and shifts in the trend, and typically
    handles outliers well.
  doc_url: https://facebook.github.io/prophet/docs/quick_start.html
  dev_url: https://github.com/facebook/prophet

extra:
  recipe-maintainers:
    - bletham
    - maresb
    - WardBrian
