{% set name = "prophet" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 963b117d56fe0dabc247b5b36cdb20d7ce7ac6899e77ec4037040b773a713ffe

build:
  number: 0
  script_env:
    - PROPHET_REPACKAGE_CMDSTAN=false
    - PRECOMPILED_HEADERS=false
  script: {{ PYTHON }} -m pip install . -vv
  binary_has_prefix_files:
    - {{ SP_DIR|replace("\\", "/") }}/stan_model/prophet_model.bin
  ignore_prefix_files:
    - bin/cmdstan/src/stan/model/model_header.hpp.gch
    - bin/cmdstan/src/stan/model/main.d
    - bin/cmdstan/src/cmdstan/main.d

requirements:
  build:
    # Ref: <https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock>
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - python
    - pip
    - cython >=0.22
    - cmdstanpy >=1.0.1
    - cmdstan ==2.29.2
    - setuptools >=42
    - wheel >=0.37.0

  run:
    - python
    - cython >=0.22
    - cmdstanpy >=1.0.1
    - cmdstan ==2.29.2
    - pandas >=1.0.4
    - matplotlib-base >=2.0.0
    - LunarCalendar >=0.0.9
    - convertdate >=2.1.2
    - holidays >=0.13
    - setuptools >=42
    - wheel >=0.37.0
    - setuptools-git >=1.2
    - python-dateutil >=2.8.0
    - tqdm >=4.36.1
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - prophet
    - prophet.tests
  commands:
    - pip check
    - py.test -v --pyargs prophet
  requires:
    - pip
    - pytest

about:
  home: https://facebook.github.io/prophet/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic Forecasting Procedure
  description: |
    Implements a procedure for forecasting time series data based on an
    additive model where non-linear trends are fit with yearly, weekly, and
    daily seasonality, plus holiday effects. It works best with time series
    that have strong seasonal effects and several seasons of historical data.
    Prophet is robust to missing data and shifts in the trend, and typically
    handles outliers well.
  doc_url: https://facebook.github.io/prophet/docs/quick_start.html
  dev_url: https://github.com/facebook/prophet

extra:
  recipe-maintainers:
    - bletham
    - maresb
    - WardBrian
